export default {
    aces: 0,
    twos: 0,
    threes: 0,
    fours: 0,
    fives: 0,
    sixes: 0,
    bonus: 0,
    pair: 0,
    dbPair: 0,
    threeOfAKind: 0,
    fourOfAKind: 0,
    fullHouse: 0,
    smStraight: 0,
    lgStraight: 0,
    yathzee: 0,
    chance: 0,
    total: 0,
}