export default {
    containerBig: {
        flex: 1,
        backgroundColor: '#000000',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    container: {
        width: '100%',
        height: '100%',
        flex: 1,
        backgroundColor: 'green',
        padding: 0,
        margin: 0,
    },
    header: {
        alignContent: 'center',
        justifyContent: 'center',
        flex: 0.5,
    },
    score: {
        backgroundColor: 'red',
        alignSelf: 'stretch',
    },
    dices: {
        backgroundColor: 'blue',
        width: '100%',
    },
    lineThree: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'center',
        padding: '3%',
        flexDirection: "row",
        flexWrap: "wrap",
    },
    button: {
        margin: 0,
        backgroundColor: 'orange',
        paddingVertical: 10,
        borderRadius: 10,
        width: 100,
        marginBottom: 20,
        marginLeft: 5,
        marginRight: 5,
    },
    buttonValid: {
        backgroundColor: 'orange',
        borderRadius: 10,
        width: '80%',
        alignSelf: 'center',
        backgroundColor: 'green',
        borderRadius: 100,
    },
}