export default {
    containerBig: {
        flex: 1,
        backgroundColor: '#000000',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    container: {
        width: '100%',
        height: '100%',
        flex: 1,
        padding: 0,
        margin: 0,
    },
    header: {
        alignContent: 'center',
        justifyContent: 'center',
        flex: 0.5,
    },
    score: {
        alignSelf: 'stretch',
        borderWidth: 1,
        borderRadius: 10,
        borderColor: 'white',
        paddingTop: 10,
        marginBottom: 20,
        height: 300,
    },
    dices: {
        width: '100%',
    },
    lineThree: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'center',
        padding: '3%',
        flexDirection: "row",
        flexWrap: "wrap",
    },
    button: {
        margin: 0,
        borderRadius: 10,
        width: 100,
        marginTop: 10,
        marginLeft: 5,
        marginRight: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonValid: {
        borderRadius: 100,
        paddingVertical: 10,
        paddingHorizontal: 80, 
        alignSelf: 'center',
        backgroundColor: 'green',
        padding: 5,
        marginTop: 30,
    },
    text: {
        color: 'white',
        fontSize: 18,
    },
    title: {
        fontSize: 22,
        fontWeight: '700',
    },
    textButton: {
        color: 'black',
    },
    textToDo: {
        marginLeft: 20,
        fontWeight: '700',
    },
}